name: Create release

on:
  workflow_dispatch:

jobs:
  changelog:
    name: Create changelog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate changelog and determine version
        id: changelog
        uses: TriPSs/conventional-changelog-action@v6
        with:
          preset: conventionalcommits
          github-token: ${{ secrets.GH_AIDE_TOKEN }}
          git-user-name: ${{ github.actor }}
          git-user-email: ${{ github.actor }}@users.noreply.github.com
          tag-prefix: ''
          input-file: 'CHANGELOG.md'
          output-file: 'CHANGELOG.md'
          release-count: 10000
          skip-on-empty: false
          version-file: 'pyproject.toml'
          version-path: 'project.version'

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          token: ${{ secrets.GH_AIDE_TOKEN }}
